/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.column_defines.conf
 */
#ifndef SCANMYNET_COLUMNS_H
#define SCANMYNET_COLUMNS_H

/* column number definitions for table smnDevicesTable */
       #define COLUMN_TABID		1
       #define COLUMN_DATETIME		2
       #define COLUMN_IPDEVICEADDRESS		3
       #define COLUMN_ISROUTER		4
       #define COLUMN_MACADDRESS		5
       #define COLUMN_MACVENDOR		6
#endif /* SCANMYNET_COLUMNS_H */
