/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.old-api.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "scanmynet.h"

/* 
 * scanmynet_variables_oid:
 *   this is the top level oid that we want to register under.  This
 *   is essentially a prefix, with the suffix appearing in the
 *   variable below.
 */

oid scanmynet_variables_oid[] = { 1,3,6,1,3,1 };

/* 
 * variable4 scanmynet_variables:
 *   this variable defines function callbacks and type return information 
 *   for the scanmynet mib section 
 */

struct variable4 scanmynet_variables[] = {
/*  magic number        , variable type , ro/rw , callback fn  , L, oidsuffix */
#define SMNTARGET		1
{SMNTARGET,  ASN_IPADDRESS,  NETSNMP_OLDAPI_RWRITE,
 var_scanmynet, 1,  { 1 }},
#define SMNJUMP		2
{SMNJUMP,  ASN_INTEGER,  NETSNMP_OLDAPI_RWRITE,
 var_scanmynet, 1,  { 2 }},
#define SMNSIMUALTE		3
{SMNSIMUALTE,  ASN_INTEGER,  NETSNMP_OLDAPI_RWRITE,
 var_scanmynet, 1,  { 3 }},
#define SMNSCANSTART		4
{SMNSCANSTART,  ASN_TIMETICKS,  NETSNMP_OLDAPI_RWRITE,
 var_scanmynet, 1,  { 4 }},
#define SMNDEVICESNUMBER		5
{SMNDEVICESNUMBER,  ASN_COUNTER,  NETSNMP_OLDAPI_RONLY,
 var_scanmynet, 1,  { 5 }},

#define TABID		1
{TABID,  ASN_INTEGER,  NETSNMP_OLDAPI_RONLY,
 var_smnDevicesTable, 3,  { 6 , 1, 1 }},
#define DATETIME		2
{DATETIME,  ASN_OCTET_STR,  NETSNMP_OLDAPI_RONLY,
 var_smnDevicesTable, 3,  { 6 , 1, 2 }},
#define IPDEVICEADDRESS		3
{IPDEVICEADDRESS,  ASN_IPADDRESS,  NETSNMP_OLDAPI_RONLY,
 var_smnDevicesTable, 3,  { 6 , 1, 3 }},
#define ISROUTER		4
{ISROUTER,  ASN_INTEGER,  NETSNMP_OLDAPI_RONLY,
 var_smnDevicesTable, 3,  { 6 , 1, 4 }},
#define MACADDRESS		5
{MACADDRESS,  ASN_OCTET_STR,  NETSNMP_OLDAPI_RONLY,
 var_smnDevicesTable, 3,  { 6 , 1, 5 }},
#define MACVENDOR		6
{MACVENDOR,  ASN_OCTET_STR,  NETSNMP_OLDAPI_RONLY,
 var_smnDevicesTable, 3,  { 6 , 1, 6 }},
};
/*    (L = length of the oidsuffix) */


/** Initializes the scanmynet module */
void
init_scanmynet(void)
{

    DEBUGMSGTL(("scanmynet", "Initializing\n"));

    /* register ourselves with the agent to handle our mib tree */
    REGISTER_MIB("scanmynet", scanmynet_variables, variable4,
               scanmynet_variables_oid);

    /* place any other initialization junk you need here */
}

/*
 * var_scanmynet():
 *   This function is called every time the agent gets a request for
 *   a scalar variable that might be found within your mib section
 *   registered above.  It is up to you to do the right thing and
 *   return the correct value.
 *     You should also correct the value of "var_len" if necessary.
 *
 *   Please see the documentation for more information about writing
 *   module extensions, and check out the examples in the examples
 *   and mibII directories.
 */
unsigned char *
var_scanmynet(struct variable *vp, 
                oid     *name, 
                size_t  *length, 
                int     exact, 
                size_t  *var_len, 
                WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    static unsigned char string[SPRINT_MAX_LEN];
    static oid objid[MAX_OID_LEN];
    static struct counter64 c64;

    if (header_generic(vp,name,length,exact,var_len,write_method)
                                  == MATCH_FAILED )
    return NULL;

    /* 
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case SMNTARGET:
        *write_method = write_smnTarget;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case SMNJUMP:
        *write_method = write_smnJump;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case SMNSIMUALTE:
        *write_method = write_smnSimualte;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case SMNSCANSTART:
        *write_method = write_smnScanStart;
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case SMNDEVICESNUMBER:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    default:
      ERROR_MSG("");
    }
    return NULL;
}


/*
 * var_smnDevicesTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_scanmynet above.
 */
unsigned char *
var_smnDevicesTable(struct variable *vp,
    	    oid     *name,
    	    size_t  *length,
    	    int     exact,
    	    size_t  *var_len,
    	    WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    static unsigned char string[SPRINT_MAX_LEN];
    static oid objid[MAX_OID_LEN];
    static struct counter64 c64;

    /* 
   * This assumes that the table is a 'simple' table.
   *	See the implementation documentation for the meaning of this.
   *	You will need to provide the correct value for the TABLE_SIZE parameter
   *
   * If this table does not meet the requirements for a simple table,
   *	you will need to provide the replacement code yourself.
   *	Mib2c is not smart enough to write this for you.
   *    Again, see the implementation documentation for what is required.
   */
    if (header_simple_table(vp,name,length,exact,var_len,write_method, TABLE_SIZE)
                                                == MATCH_FAILED )
    return NULL;

    /* 
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case TABID:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case DATETIME:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case IPDEVICEADDRESS:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case ISROUTER:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case MACADDRESS:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    case MACVENDOR:
        VAR = VALUE;	/* XXX */
        return (u_char*) &VAR;
    default:
      ERROR_MSG("");
    }
    return NULL;
}



int
write_smnTarget(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    in_addr_t value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_IPADDRESS) {
              fprintf(stderr, "write to scanmynet not ASN_IPADDRESS\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(in_addr_t)) {
              fprintf(stderr,"write to scanmynet: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (in_addr_t *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}


int
write_smnJump(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to scanmynet not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to scanmynet: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}


int
write_smnSimualte(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_INTEGER) {
              fprintf(stderr, "write to scanmynet not ASN_INTEGER\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(long)) {
              fprintf(stderr,"write to scanmynet: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}


int
write_smnScanStart(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    u_long value;
    int size;

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_TIMETICKS) {
              fprintf(stderr, "write to scanmynet not ASN_TIMETICKS\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > sizeof(u_long)) {
              fprintf(stderr,"write to scanmynet: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
          size  = var_val_len;
          value = * (u_long *) var_val;

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
             /*
              * The variable has been stored in 'value' for you to use,
              * and you have just been asked to do something with it.
              * Note that anything done here must be reversable in the UNDO case
              */
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}

