/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.old-api.conf
 */
#ifndef SCANMYNET_H
#define SCANMYNET_H

/* function declarations */
void init_scanmynet(void);
FindVarMethod var_scanmynet;
FindVarMethod var_smnDevicesTable;
    WriteMethod write_smnTarget;
    WriteMethod write_smnJump;
    WriteMethod write_smnSimualte;
    WriteMethod write_smnScanStart;

#endif /* SCANMYNET_H */
